devices([
  "iPhone 16 Pro Max"
])

languages([
  "nl-NL"
])

scheme("VIB UITests")

output_directory("./fastlane/screenshots")

clear_previous_screenshots false

override_status_bar true
override_status_bar_arguments "--time 9:41 --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --cellularBars 4 --batteryState charged --batteryLevel 100"
concurrent_simulators false

localize_simulator true